from ...callback_runtime import *

def update_UVlabel1(env, *args):
    IvsU_buttom = env.get('IvsU_buttom')
    IvsV_buttom = env.get('IvsV_buttom')
    U_lavel = env.get('U_lavel')
    V_lavel = env.get('V_lavel')
    addIvsU_buttom = env.get('addIvsU_buttom')
    addIvsV_buttom = env.get('addIvsV_buttom')
    binU_label = env.get('binU_label')
    binV_label = env.get('binV_label')
    calc_add_constU_buttom = env.get('calc_add_constU_buttom')
    calc_add_constV_buttom = env.get('calc_add_constV_buttom')
    calc_constU_buttom = env.get('calc_constU_buttom')
    calc_constV_buttom = env.get('calc_constV_buttom')
    constE_buttom = env.get('constE_buttom')
    constU_buttom = env.get('constU_buttom')
    constV_buttom = env.get('constV_buttom')
    deltaU = env.get('deltaU')
    deltaV = env.get('deltaV')
    entry_u_var = env.get('entry_u_var')
    entry_v_var = env.get('entry_v_var')
    filemenu = env.get('filemenu')
    initialU_label = env.get('initialU_label')
    initialV_label = env.get('initialV_label')
    maxU_label = env.get('maxU_label')
    maxV_label = env.get('maxV_label')
    minU_label = env.get('minU_label')
    minV_label = env.get('minV_label')
    pmU_lavel = env.get('pmU_lavel')
    pmV_lavel = env.get('pmV_lavel')
    save_menu_index1 = env.get('save_menu_index1')
    save_menu_index2 = env.get('save_menu_index2')
    save_menu_index3 = env.get('save_menu_index3')
    save_menu_index4 = env.get('save_menu_index4')
    save_menu_index5 = env.get('save_menu_index5')
    save_menu_index6 = env.get('save_menu_index6')
    save_menu_index7 = env.get('save_menu_index7')
    save_menu_index8 = env.get('save_menu_index8')
    save_menu_index9 = env.get('save_menu_index9')
    scatter3d_buttom = env.get('scatter3d_buttom')
    vr_U_label = env.get('vr_U_label')
    vr_V_label = env.get('vr_V_label')
    u_text = entry_u_var.get()
    v_text = entry_v_var.get()

    # 3d view, 2d viewボタン
    constE_buttom.set(f"{u_text} vs {v_text}")
    constV_buttom.set(f"{v_text} vs ℏω")
    constU_buttom.set(f"{u_text} vs ℏω")
    # 3d scatterボタン
    scatter3d_buttom.set(f"{u_text} vs {v_text} vs ℏω")
    # 3d viewのラベル
    initialV_label.set(f"initial {v_text}")
    initialU_label.set(f"initial {u_text}")
    vr_V_label.set(f"{v_text}")
    vr_U_label.set(f"{u_text}")
    # 1d viewのボタン
    IvsU_buttom.set(f"{u_text} vs I")
    addIvsU_buttom.set(f"add {u_text} vs I")
    IvsV_buttom.set(f"{v_text} vs I")
    addIvsV_buttom.set(f"add {v_text} vs I")
    # data constructionのラベル
    minU_label.set(f"min {u_text}")
    maxU_label.set(f"max {u_text}")
    binU_label.set(f"bin {u_text}")
    minV_label.set(f"min {v_text}")
    maxV_label.set(f"max {v_text}")
    binV_label.set(f"bin {v_text}")
    # 2d view,1d viewのラベル
    U_lavel.set(f"{u_text}")
    V_lavel.set(f"{v_text}")
    pmU_lavel.set(f"±{u_text}")
    pmV_lavel.set(f"±{v_text}")
    # calculationのラベル
    calc_constU_buttom.set(f"const {u_text}")
    calc_constV_buttom.set(f"const {v_text}")
    calc_add_constU_buttom.set(f"add const {u_text}")
    calc_add_constV_buttom.set(f"add const {v_text}")
    # smoothingのラベル
    deltaU.set(f"δ{u_text}")
    deltaV.set(f"δ{v_text}")

    # saveのラベル
    # メニューのラベルを更新
    filemenu.entryconfig(save_menu_index1, label=f"2D {u_text} vs {v_text}")
    filemenu.entryconfig(save_menu_index2, label=f"2D {v_text} vs ℏω")
    filemenu.entryconfig(save_menu_index3, label=f"2D {u_text} vs ℏω")
    filemenu.entryconfig(save_menu_index4, label=f"1D {u_text} vs I")
    filemenu.entryconfig(save_menu_index5, label=f"1D {v_text} vs I")
    filemenu.entryconfig(save_menu_index6, label=f"advanced 2D {u_text} vs {v_text}")
    filemenu.entryconfig(save_menu_index7, label=f"2D {entry_u_var.get()} vs {entry_v_var.get()} scattering data")
    filemenu.entryconfig(save_menu_index8, label=f"2D {entry_v_var.get()} vs hw scattering data")
    filemenu.entryconfig(save_menu_index9, label=f"2D {entry_u_var.get()} vs hw scattering data")
